name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install doctl
        run: |
          wget https://github.com/digitalocean/doctl/releases/download/v1.110.0/doctl-1.110.0-linux-amd64.tar.gz
          tar xf doctl-*.tar.gz
          sudo mv doctl /usr/local/bin

      - name: Authenticate with Digital Ocean
        run: |
          doctl auth init -t ${{ secrets.DO_AUTH_TOKEN }} 

      - name: Create Droplet
        run: |
          doctl compute droplet create --image docker-20-04 --size s-1vcpu-1gb --region nyc1 --vpc-uuid ba5f81a6-5df2-4149-ad14-10cb12440d95 kong-api-gtw
      
      - name: Get Droplet IP
        id: droplet
        run: |
          echo "::set-output name=ip::$(doctl compute droplet list --format PublicIPv4 --no-header | head -n 1)"

      - name: Set up SSH
        run: |
          eval "$(ssh-agent -s)"
          ssh-add ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy configuration file
        run: |
          pwd 
        # scp -o StrictHostKeyChecking=no /src root@${{ steps.droplet.outputs.ip }}:/root/src
      
      - name: Deploy to Digital Ocean
        run: |
          # ssh -o StrictHostKeyChecking=no root@${{ steps.droplet.outputs.ip }} "cd /src/docker-compose/directory && docker-compose -f docker-compose.yml pull && docker-compose -f docker-compose.yml up -d"
