name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code [MyBurger ≡]
        uses: actions/checkout@v4
      
      - name: Set up DigitalOcean [MyBurger ≡]
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_AUTH_TOKEN }}

      - name: Get First Droplet ID [MyBurger ≡]
        run: |
          DROPLET_IP=$(doctl compute droplet list 'my-burger-api-gtw' --format 'Public IPv4' --no-header | head -n 1)
          echo "DROPLET_IP=$DROPLET_IP" >> $GITHUB_ENV

      - name: Run a multi-line script
        run: |
          mkdir ../terraform
          cp -TR ./src ../terraform
          tar -cvf terraform.tar ../terraform/

      - name: copy file via ssh password
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ env.DROPLET_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "terraform.tar"
          target: "src"
          timeout: 120s
        
      - name: Deploy to Digital Ocean droplet via SSH action
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.DROPLET_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            apt-get -y install docker-compose
            cd src/
            tar xvf terraform.tar
            cd terraform/
            docker-compose -f docker-compose.yml pull
            docker-compose -f docker-compose.yml up -d
