name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code [MyBurger ≡]
        uses: actions/checkout@v4
      
      - name: Set up DigitalOcean [MyBurger ≡]
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_TOKEN_ACCESS }}

      - name: Get First Droplet ID [MyBurger ≡]
        run: |
          DROPLET_IP=$(doctl compute droplet list 'my-burger-api-gtw' --format 'Public IPv4' --no-header | head -n 1)
          echo "DROPLET_IP=$DROPLET_IP" >> $GITHUB_ENVdoctl compute ssh-key list

      - name: Deploy to Digital Ocean
        run: |
          # ssh -o StrictHostKeyChecking=no root@${{ env.DROPLET_IP }} "cd /src/docker-compose/directory && docker-compose -f docker-compose.yml pull && docker-compose -f docker-compose.yml up -d"